### ISSUE TITLE
Observable ClazzBundle 'undefined' ClassCastException

### ISSUE THREAD

**Issue by BenDol** [ltearno/hexa.tools#8]
```
Mon Aug 10 01:35:28 GMT+1200 2015 nz.co.doltech.wayhome.client.Application$PreApplicationImpl
SEVERE: undefinedjava.lang.ClassCastException
    at Unknown.fillInStackTrace(Throwable.java:116)
    at Unknown.Throwable(Throwable.java:55)
    at Unknown.Exception(Exception.java:25)
    at Unknown.RuntimeException(RuntimeException.java:25)
    at Unknown.ClassCastException(ClassCastException.java:23)
    at Unknown.dynamicCast(Cast.java:59)
    at Unknown.$clinit_ObservableSetting(ObservableSetting.java:33)
    at Unknown.ObservableSetting_0(ObservableSetting.java:46)
    at Unknown.setSetting_0(SettingForm.java:44)
    at Unknown.bindSettingForm(HomeView.java:101)
    at Unknown.setSetting(HomePresenter.java:203)
    at Unknown.onSuccess_28(HomePresenter.java:193)
    at Unknown.onSuccess_29(HomePresenter.java:189)
    at Unknown.onExecuteSuccess(DispatchCall.java:134)
    at Unknown.onExecuteSuccess_0(DispatchCall.java:144)
    at Unknown.onExecuteSuccess_1(RestDispatchCall.java:108)
    at Unknown.onResponseReceived(RestDispatchCall.java:148)
    at Unknown.onResponseReceived_0(RestDispatchCall.java:132)
    at Unknown.fireOnResponseReceived(Request.java:250)
    at Unknown.onReadyStateChange(RequestBuilder.java:412)
    at Unknown.anonymous(XMLHttpRequest.java:329)
    at Unknown.apply_0(Impl.java:247)
    at Unknown.entry0(Impl.java:299)
    at Unknown.anonymous(Impl.java:72)
```

Everything works fine until I recompiling in SuperDevMode when I make changes

It seems to be failing when calling:

``` java
    static
    {
        GWT.<ClassBundle>create( ClassBundle.class ).register();
    }
```

inside the Observable generated class, not sure why this happens sometimes. I implemented it this way:

``` java
    public void setSetting(Setting setting) {
        this.setting = new ObservableSetting(setting);

        Binder.bindObject(this.setting).mapTo(this);
        Binder.bind(this.setting, "type")
            .withConverter(new EnumConverter(SettingType.values()))
            .to(typeBox);
    }

    public Setting getSetting() {
        return setting;
    }
```

**Comment by BenDol** [comment]
https://github.com/ltearno/hexa.tools/commit/f7052ffd3ac0d6a5541094084e988de118842071 this should resolve this issue, testing atm.
